### ISSUE TITLE
Pass configuration (service application) as argument to the core

### ISSUE THREAD

**Issue by bugraderre** [proofdock/chaos-middleware-python#12]

**Comment by mkaszub** [comment]
@bugraderre 

Configuration of middleware should be pass to the core as dict-like object. 

For different implementation of the middleware e.g: flask, configuration should be read from flask specific config object (flask.app.config). In such case user is responsible for setting configuration of the middleware using flask config mechanism. After flask-specific middleware read the config it should be passed to the core.

If user use only core functionality he is responsible for configuring the core manually by passing to it configuration object.
